status = ["build", "docs"]
pr_status = ["build", "docs"]
required_approvals = 1
delete_merged_branches = false
use_codeowners = false
use_squash_merge = false
commit_title = "Auto merge of ${PR_REFS}"
