status = [
    "%-unknown-linux-gnu",
    "Build documentation and books"
]
pr_status = [
    "%-unknown-linux-gnu",
    "Build documentation and books"
]
required_approvals = 0
delete_merged_branches = false
use_codeowners = false
use_squash_merge = false
commit_title = "Auto merge of ${PR_REFS}"
