#!/usr/bin/env python

import subprocess
import sys

def main():
    print("Running `cargo check --workspace --all-features --all-targets`...")
    res = subprocess.run(["cargo", "check", "--workspace", "--all-features", "--all-targets"])
    if res.returncode != 0:
        print("Failure while building code.\nCommit aborted.")
        return
    
    print("Running `cargo test --workspace --all-features`...")
    res = subprocess.run(["cargo", "test", "--workspace", "--all-features"])
    if res.returncode != 0:
        print("Failure while testing code.\nCommit aborted.")
        sys.exit(-1)

    print("Checking code for formatting errors...")
    res = subprocess.run(["cargo", "fmt", "--", "--check"])
    if res.returncode != 0:
        print("A formatting error was detected. See the above diff or use `cargo fmt` to\nresolve it.\nCommit aborted.")
        sys.exit(-1)

if __name__ == "__main__":
    main()
